name: Build Linux Containers daily

# on:
#  schedule:
#  - cron:   '55 4 * * *'

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    name: Build all containers

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 10
   
    - name: Build all
      run: |
        ./jenkins.sh
