name: Build CentOS Linux Containers daily

on:
  workflow_dispatch:
  schedule:
  - cron:   '15 4 * * *'

jobs:

  centos-epel:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 10
    - name: Build
      run: |
        ./build-image.sh centos-epel --no-cache
      env:
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
