name: Build Fedora Linux Containers daily

on:
  workflow_dispatch:
  schedule:
  - cron:   '55 4 * * *'

jobs:

  fedora:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 10
    - name: Build
      run: |
        ./build-image.sh fedora --no-cache
      env:
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

  fedora-clang:
    runs-on: ubuntu-latest
    needs: fedora
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 10
    - name: Build
      run: |
        ./build-image.sh fedora-clang --no-cache
      env:
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

  fedora-clang-devel:
    runs-on: ubuntu-latest
    needs: fedora-clang
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 10
    - name: Build
      run: |
        ./build-image.sh fedora-clang-devel --no-cache
      env:
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

  fedora-clang-devel-san:
    runs-on: ubuntu-latest
    needs: fedora-clang-devel
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 10
    - name: Build
      run: |
        ./build-image.sh fedora-clang-devel-san --no-cache
      env:
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

  fedora-gcc:
    runs-on: ubuntu-latest
    needs: fedora
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 10
    - name: Build
      run: |
        ./build-image.sh fedora-gcc --no-cache
      env:
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

  fedora-gcc-devel:
    runs-on: ubuntu-latest
    needs: fedora-gcc
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 10
    - name: Build
      run: |
        ./build-image.sh fedora-gcc-devel --no-cache
      env:
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
